services:
  web:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - react

  react:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"