# Utilisez une image python comme base
From python:3.12.4
# Définissez le répertoire de travail dans le conteneur
WORKDIR /main
# Copiez les fichiers de votre projet dans le conteneur
COPY requirements.txt .
# Installez les dépendances
RUN pip install --no-cache-dir -r requirements.txt
# Copiez le reste de votre code dans le conteneur
COPY . .
# Exposez le port sur lequel votre application écoute (si nécessaire)
EXPOSE 8000
# Commande pour exécuter votre application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]


